#! /bin/bash
#SBATCH --partition=uoa-compute
#SBATCH --ntasks=24
#SBATCH --time=05:00:00
#SBATCH --mem-per-cpu=8g
#SBATCH --mail-type=ALL
#SBATCH --mail-user=m.tawfik.19@abdn.ac.uk

printf " \n"
echo "Pedal to the metal!"
printf " \n"

#loading the necessary TrimGalore software module
echo "loading required modules"
printf "\n"

module load FastQC-0.11.8
module load TrimGalore-0.6.4
module load parallel-20200222
parallel --citation

# Define an array with all the sample names
sample_names=(
"water-MMV-T1-Rep1"
"water-MMV-T1-Rep1"
"water-MMV-T9-Rep2"
"water-MMV-T9-Rep2"
"water-VMV-T12-Rep3"
"water-VMV-T12-Rep3"
"water-VMV-T3-Rep1"
"water-VMV-T3-Rep1"
"water-VMV-T3+12-Rep4"
"water-VMV-T3+12-Rep4"
"water-VMV-T8-Rep2"
"water-VMV-T8-Rep2"
"distal-MMV-T1-Rep1"
"distal-MMV-T1-Rep1"
"distal-MMV-T1-Rep2"
"distal-MMV-T1-Rep2"
"distal-MMV-T1-Rep3"
"distal-MMV-T1-Rep3"
"distal-MMV-T1-Rep4"
"distal-MMV-T1-Rep4"
"distal-MMV-T1-Rep5"
"distal-MMV-T1-Rep5"
"distal-MMV-T1-Rep6"
"distal-MMV-T1-Rep6"
"distal-MMV-T5-Rep1"
"distal-MMV-T5-Rep1"
"distal-MMV-T5-Rep2"
"distal-MMV-T5-Rep2"
"distal-MMV-T5-Rep3"
"distal-MMV-T5-Rep3"
"distal-MMV-T5-Rep4"
"distal-MMV-T5-Rep4"
"distal-MMV-T5-Rep5"
"distal-MMV-T5-Rep5"
"distal-MMV-T5-Rep6"
"distal-MMV-T5-Rep6"
"distal-MMV-T9-Rep1"
"distal-MMV-T9-Rep1"
"distal-MMV-T9-Rep2"
"distal-MMV-T9-Rep2"
"distal-MMV-T9-Rep3"
"distal-MMV-T9-Rep3"
"distal-MMV-T9-Rep4"
"distal-MMV-T9-Rep4"
"distal-MMV-T9-Rep5"
"distal-MMV-T9-Rep5"
"distal-MMV-T9-Rep6"
"distal-MMV-T9-Rep6"
"distal-VMV-T12-Rep1"
"distal-VMV-T12-Rep1"
"distal-VMV-T12-Rep2"
"distal-VMV-T12-Rep2"
"distal-VMV-T12-Rep3"
"distal-VMV-T12-Rep3"
"distal-VMV-T12-Rep4"
"distal-VMV-T12-Rep4"
"distal-VMV-T12-Rep5"
"distal-VMV-T12-Rep5"
"distal-VMV-T12-Rep6"
"distal-VMV-T12-Rep6"
"distal-VMV-T3-Rep1"
"distal-VMV-T3-Rep1"
"distal-VMV-T3-Rep2"
"distal-VMV-T3-Rep2"
"distal-VMV-T3-Rep3"
"distal-VMV-T3-Rep3"
"distal-VMV-T3-Rep4"
"distal-VMV-T3-Rep4"
"distal-VMV-T3-Rep5"
"distal-VMV-T3-Rep5"
"distal-VMV-T3-Rep6"
"distal-VMV-T3-Rep6"
"distal-VMV-T8-Rep1"
"distal-VMV-T8-Rep1"
"distal-VMV-T8-Rep2"
"distal-VMV-T8-Rep2"
"distal-VMV-T8-Rep3"
"distal-VMV-T8-Rep3"
"distal-VMV-T8-Rep4"
"distal-VMV-T8-Rep4"
"distal-VMV-T8-Rep5"
"distal-VMV-T8-Rep5"
"distal-VMV-T8-Rep6"
"distal-VMV-T8-Rep6"
"middle-MMV-T1-Rep1"
"middle-MMV-T1-Rep1"
"middle-MMV-T1-Rep2"
"middle-MMV-T1-Rep2"
"middle-MMV-T1-Rep3"
"middle-MMV-T1-Rep3"
"middle-MMV-T1-Rep4"
"middle-MMV-T1-Rep4"
"middle-MMV-T1-Rep5"
"middle-MMV-T1-Rep5"
"middle-MMV-T1-Rep6"
"middle-MMV-T1-Rep6"
"middle-MMV-T5-Rep1"
"middle-MMV-T5-Rep1"
"middle-MMV-T5-Rep2"
"middle-MMV-T5-Rep2"
"middle-MMV-T5-Rep3"
"middle-MMV-T5-Rep3"
"middle-MMV-T5-Rep4"
"middle-MMV-T5-Rep4"
"middle-MMV-T5-Rep5"
"middle-MMV-T5-Rep5"
"middle-MMV-T5-Rep6"
"middle-MMV-T5-Rep6"
"middle-MMV-T9-Rep1"
"middle-MMV-T9-Rep1"
"middle-MMV-T9-Rep2"
"middle-MMV-T9-Rep2"
"middle-MMV-T9-Rep3"
"middle-MMV-T9-Rep3"
"middle-MMV-T9-Rep4"
"middle-MMV-T9-Rep4"
"middle-MMV-T9-Rep5"
"middle-MMV-T9-Rep5"
"middle-MMV-T9-Rep6"
"middle-MMV-T9-Rep6"
"middle-VMV-T12-Rep1"
"middle-VMV-T12-Rep1"
"middle-VMV-T12-Rep2"
"middle-VMV-T12-Rep2"
"middle-VMV-T12-Rep3"
"middle-VMV-T12-Rep3"
"middle-VMV-T12-Rep4"
"middle-VMV-T12-Rep4"
"middle-VMV-T12-Rep5"
"middle-VMV-T12-Rep5"
"middle-VMV-T12-Rep6"
"middle-VMV-T12-Rep6"
"middle-VMV-T3-Rep1"
"middle-VMV-T3-Rep1"
"middle-VMV-T3-Rep2"
"middle-VMV-T3-Rep2"
"middle-VMV-T3-Rep3"
"middle-VMV-T3-Rep3"
"middle-VMV-T3-Rep4"
"middle-VMV-T3-Rep4"
"middle-VMV-T3-Rep5"
"middle-VMV-T3-Rep5"
"middle-VMV-T3-Rep6"
"middle-VMV-T3-Rep6"
"middle-VMV-T8-Rep1"
"middle-VMV-T8-Rep1"
"middle-VMV-T8-Rep2"
"middle-VMV-T8-Rep2"
"middle-VMV-T8-Rep3"
"middle-VMV-T8-Rep3"
"middle-VMV-T8-Rep4"
"middle-VMV-T8-Rep4"
"middle-VMV-T8-Rep5"
"middle-VMV-T8-Rep5"
"middle-VMV-T8-Rep6"
"middle-VMV-T8-Rep6"
"feed-M-Rep1"
"feed-M-Rep1"
"feed-M-Rep2"
"feed-M-Rep2"
"feed-M-Rep3"
"feed-M-Rep3"
"negative-2"
"negative-2"
"negative-3"
"negative-3"
"negative-1"
"negative-1"
"positive-2"
"positive-2"
"positive-1"
"positive-1"
"pyloric-MMV-T1-Rep1"
"pyloric-MMV-T1-Rep1"
"pyloric-MMV-T1-Rep2"
"pyloric-MMV-T1-Rep2"
"pyloric-MMV-T1-Rep3"
"pyloric-MMV-T1-Rep3"
"pyloric-MMV-T1-Rep4"
"pyloric-MMV-T1-Rep4"
"pyloric-MMV-T1-Rep5"
"pyloric-MMV-T1-Rep5"
"pyloric-MMV-T1-Rep6"
"pyloric-MMV-T1-Rep6"
"pyloric-MMV-T5-Rep1"
"pyloric-MMV-T5-Rep1"
"pyloric-MMV-T5-Rep2"
"pyloric-MMV-T5-Rep2"
"pyloric-MMV-T5-Rep3"
"pyloric-MMV-T5-Rep3"
"pyloric-MMV-T5-Rep4"
"pyloric-MMV-T5-Rep4"
"pyloric-MMV-T5-Rep5"
"pyloric-MMV-T5-Rep5"
"pyloric-MMV-T5-Rep6"
"pyloric-MMV-T5-Rep6"
"pyloric-MMV-T9-Rep1"
"pyloric-MMV-T9-Rep1"
"pyloric-MMV-T9-Rep2"
"pyloric-MMV-T9-Rep2"
"pyloric-MMV-T9-Rep3"
"pyloric-MMV-T9-Rep3"
"pyloric-MMV-T9-Rep4"
"pyloric-MMV-T9-Rep4"
"pyloric-MMV-T9-Rep5"
"pyloric-MMV-T9-Rep5"
"pyloric-MMV-T9-Rep6"
"pyloric-MMV-T9-Rep6"
"pyloric-VMV-T12-Rep1"
"pyloric-VMV-T12-Rep1"
"pyloric-VMV-T12-Rep2"
"pyloric-VMV-T12-Rep2"
"pyloric-VMV-T12-Rep3"
"pyloric-VMV-T12-Rep3"
"pyloric-VMV-T12-Rep4"
"pyloric-VMV-T12-Rep4"
"pyloric-VMV-T12-Rep5"
"pyloric-VMV-T12-Rep5"
"pyloric-VMV-T12-Rep6"
"pyloric-VMV-T12-Rep6"
"pyloric-VMV-T3-Rep1"
"pyloric-VMV-T3-Rep1"
"pyloric-VMV-T3-Rep2"
"pyloric-VMV-T3-Rep2"
"pyloric-VMV-T3-Rep3"
"pyloric-VMV-T3-Rep3"
"pyloric-VMV-T3-Rep4"
"pyloric-VMV-T3-Rep4"
"pyloric-VMV-T3-Rep5"
"pyloric-VMV-T3-Rep5"
"pyloric-VMV-T3-Rep6"
"pyloric-VMV-T3-Rep6"
"pyloric-VMV-T8-Rep1"
"pyloric-VMV-T8-Rep1"
"pyloric-VMV-T8-Rep2"
"pyloric-VMV-T8-Rep2"
"pyloric-VMV-T8-Rep3"
"pyloric-VMV-T8-Rep3"
"pyloric-VMV-T8-Rep4"
"pyloric-VMV-T8-Rep4"
"pyloric-VMV-T8-Rep5"
"pyloric-VMV-T8-Rep5"
"pyloric-VMV-T8-Rep6"
"pyloric-VMV-T8-Rep6"
"feed-V-Rep1"
"feed-V-Rep1"
"feed-V-Rep2"
"feed-V-Rep2"
"feed-V-Rep3"
"feed-V-Rep3"
)

#run trim Galore across all zipped ziles
echo "running trim Galore over all fastq files"
printf "\n"

# Iterate over each sample name
for sample in "${sample_names[@]}"; do
    echo "Running TrimGalore for $sample"
    printf "\n"

echo "running TrimGalore over read pair"
printf "\n"

    trim_galore -q 30 --phred33 --paired --gzip --fastqc --fastqc_args "--nogroup" -o "./trimGalored" --length 20 --stringency 1 -e 0 --clip_R1 17 --clip_R2 21 "${sample}_R1.fq.gz" "${sample}_R2.fq.gz"
done

echo "FINITO!!"
printf "\n"

