---
title: "Alpha diversity"
author: "Marwa Tawfik"
date: "07 07 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, results="hide"}
# load libraries
library(phyloseq)
library(microeco)
library(file2meco)
library(tidyverse)
library(ggplot2)
library(SRS)
library(lmPerm)
library(rstatix)
```

```{r}
# import phyloseq and transform into microtable 
ps.prev <- readRDS("phyobjects/STEP 15/ps.prev.f.rds")
dataset <- phyloseq2meco(ps.prev)

ps.prev.intes <- readRDS("phyobjects/STEP 15/ps.prev.intes.f.rds")
dataset.intes <- phyloseq2meco(ps.prev.intes)
```

```{r}
# SRS when method = "SRS"
d1 <- clone(dataset)
d1$rarefy_samples(method = "SRS", rngseed = 123)
# View(d2$otu_table)
# d1$sample_sums()
# Use the minimum number across samples: 624
# 2023 features are removed because they are no longer present in any sample after random subsampling ...
# 2023 taxa are removed from the otu_table, as the abundance is 0 ...
ps.prev <- meco2phyloseq(d1)
```

```{r}
# SRS when method = "SRS"
d2 <- clone(dataset.intes)
d2$rarefy_samples(method = "SRS", rngseed = 123)
# View(d2$otu_table)
# d2$sample_sums()
#Use the minimum number across samples: 624
#393 features are removed because they are no longer present in any sample after random subsampling #393 taxa are removed from the otu_table, as the abundance is 0 ...
ps.prev.intes <- meco2phyloseq(d2)
```

```{r}
# use phyloseq package ----
# Calculate Observed Species (eveness), Choa1 and Shannon using estimate_richness function of PhyloSeq:
ps.prev.alpha.div <- estimate_richness(ps.prev, measures = c("Observed", "Chao1", "Shannon", "Simpson"))

ps.prev.intes.alpha.div <- estimate_richness(ps.prev.intes, measures = c("Observed", "Chao1", "Shannon", "Simpson"))

# Add metadata to make plots:
ps.prev.rich <- cbind(as.data.frame(sample_data(ps.prev)), ps.prev.alpha.div)
#write.table(ps.prev.rich, "tables/ps.prev.rich.txt", sep="\t", quote=F, col.names=NA)

ps.prev.intes.rich <- cbind(as.data.frame(sample_data(ps.prev.intes)), ps.prev.intes.alpha.div)
#write.table(ps.prev.intes.rich, "tables/ps.prev.intes.rich.txt", sep="\t", quote=F, col.names=NA)

head(ps.prev.intes.rich) # sanity check for each subset
```


```{r}
# Region are ordinal data
ps.prev.intes.rich$gut.order <- NA
ps.prev.intes.rich$gut.order[ps.prev.intes.rich$Region == "pyloric"] <- 1
ps.prev.intes.rich$gut.order[ps.prev.intes.rich$Region == "middle"] <- 2
ps.prev.intes.rich$gut.order[ps.prev.intes.rich$Region == "distal"] <- 3
class(ps.prev.intes.rich$gut.order)
```
```{r}
# check if assumption of linear model is met or not
model <- lm(Shannon ~ gut.order, data = ps.prev.intes.rich)
plot(model)
# nearly equal variance for each tested group/treatmnet (plot1)
# linearity of the model is not achieved (plot 2)
```

```{r}
# Since assumptions of linear model weren't med
# Fit a linear model with interactions on Region and Regime variables/columns

model <- lmp(Shannon ~ gut.order, data = ps.prev.intes.rich)
summary(model)

# [1] "Settings:  unique SS : numeric variables centered"
# 
# Call:
# lmp(formula = Shannon ~ gut.order, data = ps.prev.intes.rich)
# 
# Residuals:
#      Min       1Q   Median       3Q      Max 
# -1.91695 -0.96911  0.05692  1.10314  2.04428 
# 
# Coefficients:
#           Estimate Iter Pr(Prob)   
# gut.order   -0.466 5000   0.0012 **
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# Residual standard error: 1.122 on 91 degrees of freedom
# Multiple R-Squared: 0.09554,	Adjusted R-squared: 0.0856 
# F-statistic: 9.612 on 1 and 91 DF,  p-value: 0.002573 
```

```{r}
# run non-paraemtic to chek for the pairwise statitiscal signfincance
# pyloric (1) is significantly higher from distal (3) **
# group1	group3	n1=23	n2=34	statistic=574	p=0.003	p.adj=0.008	sig=**
pairwise_wilcox_test(ps.prev.intes.rich,
                               Shannon ~ gut.order,
                               p.adjust.method = "BH")
```

```{r}
pairwise_wilcox_test(ps.prev.rich,
                               Shannon ~ sample_regime,
                               p.adjust.method = "BH")
# gut is lower from water and feed under each regime (regardless of the regime)
# no stat sig. between two regimes for any sample type (MMV vs VMV): gut or feed or water 
```

```{r}
pairwise_wilcox_test(ps.prev.rich,
                               Shannon ~ sample,
                               p.adjust.method = "BH")
# gut is lower than water (****) and feed (****)
# feed is lower than water (*)
```

```{r}
#tiff("figures/fig2a.tiff", height = 5, width = 5, units = "in", res = 300, compression = "lzw")
plot(Shannon ~ jitter(gut.order, amount = 0.2), data = ps.prev.intes.rich, xlim = c(0.5, 3.5), axes = F, xlab = "Gut region", ylab = "Shannon Weiner", pch = 16)
box()
axis(2)
axis(1, at = c(1,2,3), labels = c("pyloric", "middle", "distal"))
ps.prev.intes.rich$gut.order <- as.numeric(ps.prev.intes.rich$Region)

model <- lmp(Shannon ~ gut.order, ps.prev.intes.rich)
fakeX <- seq(0, 3.5, by = 0.01)
predictedY <- predict(model, newdata = data.frame(gut.order = fakeX), se.fit = T)
lines(fakeX, predictedY$fit, lwd = 3, col = "blue")
lines(fakeX, predictedY$fit + predictedY$se.fit, lwd = 1, lty = 2, col = "blue")
lines(fakeX, predictedY$fit - predictedY$se.fit, lwd = 1, lty = 2, col = "blue")
#dev.off()
```

```{r}
ggplot(ps.prev.intes.rich, aes(x = Region, y = Shannon, color = Regime)) +
  theme_bw() +
  geom_point(size = 1.3, position = position_jitter(width = 0.2), alpha = 0.8) +
  theme(text = element_text(size = 12)) +
  labs(y = "Shannon-Weiner", x = "Region") +
  scale_color_manual(values = c("#C71585", "#008080")) 
#ggsave("figures/fig2b.tiff", height = 3, width = 4, units = "in", dpi = 300, compression = "lzw")
```

```{r}
ggplot(ps.prev.intes.rich, aes(x = Regime, y = Shannon, color = Region)) +
  theme_bw() +
  geom_point(size = 1.3, position = position_jitter(width = 0.2), alpha = 0.8) +
  theme(text = element_text(size = 12)) +
  labs(y = "Shannon-Weiner", x = "Regime") +
  scale_color_manual(values = c("#FF7F00", "#6A3D9A", "#A6CEE3"))
#ggsave("figures/fig2c.tiff", height = 3, width = 4, units = "in", dpi = 300, compression = "lzw")
```

```{r}
ggplot(ps.prev.rich, aes(x = sample, y = Shannon)) +
  theme_bw() +
  geom_point(size = 0.7, position = position_jitter(width = 0.2), alpha = 0.8) +
  theme(text = element_text(size = 12)) +
  labs(y = "Shannon-Weiner", x = "Sample type")
#ggsave("figures/fig2d.tiff", height = 3, width = 4, units = "in", dpi = 300, compression = "lzw")
```

```{r}
sessionInfo()
```

